server:
  port: 80
cors:
 originPatterns: http://localhost:8080,http://localhost:3000,https://barreto.com.br
file:
  upload-dir: /uploadDir
security:
  jwt:
    token:
      secret_key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: tpb16*2700
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false 
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB 
springdoc:
  paths-to-match: 
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true
    
    
